### ISSUE TITLE
[Feature Request] Add a configuration option for the output directory

### ISSUE THREAD

**Issue by micziz** [ThioJoe/Auto-Synced-Translated-Dubs#11]
# Why

Well people like to customize the directory for workflow stuff and to have everything cleanly in one place.

## How to implement

Just add an option in the `config.ini`, parse the variable in the script and pass it in.

If you are very busy, or have no idea on how to implement it, I (or another contributor) cloud do that for you...

## Is this feature bloat?

Depends. It cloud be implemented, see if people use it, then remove it if it's unpopular. Also, it doesn't really slow down the script...

**Comment by ThioJoe** [comment]
I might just have it output to a directory based on the original video name

**Comment by micziz** [comment]
> I might just have it output to a directory based on the original video name

You may have had a better idea than me. I think it's better...

**Comment by ThioJoe** [comment]
The latest version now dynamically changes the output folder
