### ISSUE TITLE
Can someone tell me why can't I run multiple languages separated by a comma? I can only run one language at a time

### ISSUE THREAD

**Issue by TharunDharmaraj** [ThioJoe/Auto-Synced-Translated-Dubs#23]

**Comment by ThioJoe** [comment]
Hm not sure what would cause the connection issue mentioned in the last line. Especially since it only happened after the first one worked. Does this happen every time you run it?

**Comment by TharunDharmaraj** [comment]
> Hm not sure what would cause the connection issue mentioned in the last line. Especially since it only happened after the first one worked. Does this happen every time you run it?

Yes it happens everytime I run

**Comment by ThioJoe** [comment]
Since it seems to only happen once it starts doing Thai, can you post that language entry you have set in batch.ini?
Also what happens if you set Thai as the only language to be processed, does it still do it then?

The one that looks like this, except filled in for Thai:
```
[LANGUAGE-12]
# 
translation_target_language = 
synth_language_code = 
synth_voice_name = 
synth_voice_gender = 
```

**Comment by TharunDharmaraj** [comment]
I processed about 10 languages before thai and it processed well, but from reaching thai, this error keepes showing up no matter which language i use from then...now this error keeps coming for all the languages. Even I setup the whole program once agin and it keeps showing the same. Can you tell me a method,as I tried all the methods to fix this.enabled_languages = 19
[LANGUAGE-19]
# THAI 
translation_target_language = th
synth_language_code = th-TH
synth_voice_name = th-TH-NiwatNeural
synth_voice_gender = MALE

**Comment by TharunDharmaraj** [comment]
# You can add as many sections for langauges as you need. Just add to the number in the [LANGUAGE-#] for each one
# Each section must contain the synth language code, synth voice name, and translation target language
# A value for synth_voice_gender only matters if the service requires it, like Google TTS, but the setting must be there even if not used



#neural-voices
#https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support?tabs=stt-tts
[SETTINGS]

	# Enter the language numbers you wish to process when the batch file is read.
	# This is also useful for multiple presets of a single language - You could just enable one of them at a time
	# Just enter the numbers separated by commas: For example, to use LANGUAGE-1 and LANGUAGE-2, put "1,2"
	; 0 - English(US)
	; 1 - Spanish
	; 2 - Hindi
	; 3 - Arabic
	; 4 - Russian
	; 5 - Portuguese
	; 6 - Italian
	; 7 - Indonesian
	; 8 - Japnese
	; 9 - Korean
	; 10 - German
	; 11 - Chinese(Mandarin)
	; 12 - Turkish
	; 13 - Tamil
	; 14 - French
	; 15 - Urdu
	; 16 - DUTCH
	; 17 - SWEDISH
	; 18 - Telugu
	; 19 - Thai 
	; 20 - Vietnamese
	; 21 - BULGARIAN
	; 22 - Danish
	; 23 - Norwegian
	; 24 - Croatian
	; 25 - Greek
	; 26 - English(GB)

; 1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,19,20,22
enabled_languages = 19

	# You an use a full file path, or the name of the file if it's in the same directory
	# The video file name will also be used to name the final output audio file
original_video_file_path = org_video.mp4
srt_file_path = eg.srt



[LANGUAGE-0]
# English / Testing
	# Remember, the translation target code may be different from synth_language_code because it is the one used by the translation service, not the TTS service
	# See the codes here: https://cloud.google.com/translate/docs/languages
translation_target_language = en
	# The language of the synthesized voice. Might not necessarily be exactly the same as target_language variable below
	# Examples - English: en-US    Spanish: es-us   or   es-mx
synth_language_code = en-US
	# Choose one from here so it matches the target language: https://cloud.google.com/text-to-speech/docs/voices  /   https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support?tabs=stt-tts
	# Examples - English: en-US-Neural2-I  (Google)  or  en-US-JasonNeural (Azure)  Spanish: es-US-Neural2-B (Google)  or es-MX-CecilioNeural (Azure)
synth_voice_name = en-US-JasonNeural
	# Google Only: Should match the gender of the chosen voice above
synth_voice_gender = MALE


[LANGUAGE-1]
# Spanish
translation_target_language = es
synth_language_code = es-MX
synth_voice_name = es-MX-CecilioNeural
synth_voice_gender = MALE

[LANGUAGE-2]
# Hindi
translation_target_language = hi
synth_language_code = hi-IN
synth_voice_name = hi-IN-MadhurNeural
synth_voice_gender = MALE

[LANGUAGE-3]
# Arabic
translation_target_language = ar
synth_language_code = ar-EG
synth_voice_name = ar-EG-ShakirNeural
synth_voice_gender = MALE

[LANGUAGE-4]
# Russian
translation_target_language = ru
synth_language_code = ru-RU
synth_voice_name = ru-RU-DmitryNeural
synth_voice_gender = MALE

[LANGUAGE-5]
# Portuguese
translation_target_language = pt
synth_language_code = pt-BR
synth_voice_name = pt-BR-FabioNeural
synth_voice_gender = MALE

[LANGUAGE-6]
# Italian
translation_target_language = it
synth_language_code = it-IT
synth_voice_name = it-IT-DiegoNeural
synth_voice_gender = MALE

[LANGUAGE-7]
# Indonesian
translation_target_language = id
synth_language_code = id-ID
synth_voice_name = id-ID-ArdiNeural
synth_voice_gender = MALE

[LANGUAGE-8]
# Japanese
translation_target_language = ja
synth_language_code = ja-JP
synth_voice_name = ja-JP-NaokiNeural
synth_voice_gender = MALE


[LANGUAGE-9]
# Korean
translation_target_language = ko
synth_language_code = ko-KR
synth_voice_name = ko-KR-BongJinNeural
synth_voice_gender = MALE

[LANGUAGE-10]
# German
translation_target_language = de
synth_language_code = de-DE
synth_voice_name = de-DE-KasperNeural
synth_voice_gender = MALE

[LANGUAGE-11]
# Chinese (Mandarin Simplified)
translation_target_language = zh
synth_language_code = zh-CN
synth_voice_name = zh-CN-YunyeNeural
synth_voice_gender = MALE

[LANGUAGE-12]
# Turkish
translation_target_language = tr
synth_language_code = tr-TR
synth_voice_name = tr-TR-AhmetNeural
synth_voice_gender = MALE

[LANGUAGE-13]
# TAMIL
translation_target_language = ta
synth_language_code = ta-IN
synth_voice_name = ta-IN-ValluvarNeural
synth_voice_gender = MALE

[LANGUAGE-14]
# FRENCE
translation_target_language = fr
synth_language_code = fr-FR
synth_voice_name = fr-FR-ClaudeNeural
synth_voice_gender = MALE

[LANGUAGE-15]
# URDU
translation_target_language = ur
synth_language_code = ur-PK
synth_voice_name = ur-PK-AsadNeural
synth_voice_gender = MALE

[LANGUAGE-16]
# DUTCH
translation_target_language = nl
synth_language_code = nl-NL
synth_voice_name = nl-NL-MaartenNeural
synth_voice_gender = MALE

[LANGUAGE-17]
# SWEDISH
translation_target_language = sv
synth_language_code = sv-SE
synth_voice_name = sv-SE-MattiasNeural
synth_voice_gender = MALE

[LANGUAGE-18]
# TELUGU
translation_target_language = te
synth_language_code = te-IN
synth_voice_name = te-IN-MohanNeural
synth_voice_gender = MALE

[LANGUAGE-19]
# THAI 
translation_target_language = th
synth_language_code = th-TH
synth_voice_name = th-TH-NiwatNeural
synth_voice_gender = MALE


[LANGUAGE-20]
# VIETNAMESE
translation_target_language = vi
synth_language_code = vi-VN
synth_voice_name = vi-VN-NamMinhNeural
synth_voice_gender = MALE


[LANGUAGE-21]
# BULGARIAN
translation_target_language = bg
synth_language_code = bg-BG
synth_voice_name = bg-BG-BorislavNeural
synth_voice_gender = MALE


[LANGUAGE-22]
# DANISH
translation_target_language = da
synth_language_code = da
synth_voice_name = da-DK-JeppeNeural
synth_voice_gender = MALE

[LANGUAGE-23]
# NORWEGIAN
translation_target_language = nb
synth_language_code = nb-NO
synth_voice_name = nb-NO-FinnNeural
synth_voice_gender = MALE

[LANGUAGE-24]
# CROATIAN
translation_target_language = hr
synth_language_code = hr-HR
synth_voice_name = hr-HR-SreckoNeural
synth_voice_gender = MALE

[LANGUAGE-25]
# GREEK
translation_target_language = el
synth_language_code = el-GR
synth_voice_name = el-GR-NestorasNeural
synth_voice_gender = MALE

[LANGUAGE-26]
# 
translation_target_language = en
synth_language_code = en-GB
synth_voice_name = en-GB-AlfieNeural
synth_voice_gender = MALE

[LANGUAGE-27]
# 
translation_target_language = 
synth_language_code = 
synth_voice_name = 
synth_voice_gender = MALE

[LANGUAGE-28]
# 
translation_target_language = 
synth_language_code = 
synth_voice_name = 
synth_voice_gender = MALE

[LANGUAGE-29]
# 
translation_target_language = 
synth_language_code = 
synth_voice_name = 
synth_voice_gender = MALE

**Comment by TharunDharmaraj** [comment]
I processed about 10 languages before thai and it processed well, but from reaching thai, this error keepes showing up no matter which language i use from then...now this error keeps coming for all the languages. Even I setup the whole program once again and it keeps showing the same. Can you tell me a method,as I tried all the methods to fix this.


`enabled_languages = 19
[LANGUAGE-19]

THAI
translation_target_language = th
synth_language_code = th-TH
synth_voice_name = th-TH-NiwatNeural
synth_voice_gender = MALE`


And it generates the translated srt file and all the mp3 files of that translated srt file in the working folder, but any of them cant be played. It shows that**"an error occured during opeing the file"**. I think these mp3 files cannot be read by the program.It cannot be even read by my system mp3 player. and if there is some way that can you suggest for me to correct it, as it was all working fine but suddenly it stared throwing this error and I even redone the setup but it keeps throwing the same. Pls suggest me some ways regarding this error.

Thank You

**Comment by TharunDharmaraj** [comment]
I processed about 10 languages before thai and it processed well i got the individual combined full mp3 audi files , but from reaching thai, this error keepes showing up no matter which language i use from then...now this error keeps coming for all the languages. Even I setup the whole program once again and it keeps showing the same for all the languages. The below is the "batch.ini" file

`#neural-voices
#https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support?tabs=stt-tts
[SETTINGS]
	; 0 - English(US)
	; 1 - Spanish
	; 2 - Hindi
	; 3 - Arabic
	; 4 - Russian
	; 5 - Portuguese
	; 6 - Italian
	; 7 - Indonesian
	; 8 - Japnese
	; 9 - Korean
	; 10 - German
	; 11 - Chinese(Mandarin)
	; 12 - Turkish
	; 13 - Tamil
	; 14 - French
	; 15 - Urdu
	; 16 - DUTCH
	; 17 - SWEDISH
	; 18 - Telugu
	; 19 - Thai 
	; 20 - Vietnamese
	; 21 - BULGARIAN
	; 22 - Danish
	; 23 - Norwegian
	; 24 - Croatian
	; 25 - Greek
	; 26 - English(GB)

enabled_languages = 19
original_video_file_path = org_video.mp4
srt_file_path = eg.srt



[LANGUAGE-0]
# English / Testing
	# Remember, the translation target code may be different from synth_language_code because it is the one used by the translation service, not the TTS service
	# See the codes here: https://cloud.google.com/translate/docs/languages
translation_target_language = en
	# The language of the synthesized voice. Might not necessarily be exactly the same as target_language variable below
	# Examples - English: en-US    Spanish: es-us   or   es-mx
synth_language_code = en-US
	# Choose one from here so it matches the target language: https://cloud.google.com/text-to-speech/docs/voices  /   https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support?tabs=stt-tts
	# Examples - English: en-US-Neural2-I  (Google)  or  en-US-JasonNeural (Azure)  Spanish: es-US-Neural2-B (Google)  or es-MX-CecilioNeural (Azure)
synth_voice_name = en-US-JasonNeural
	# Google Only: Should match the gender of the chosen voice above
synth_voice_gender = MALE


[LANGUAGE-1]
# Spanish
translation_target_language = es
synth_language_code = es-MX
synth_voice_name = es-MX-CecilioNeural
synth_voice_gender = MALE

[LANGUAGE-2]
# Hindi
translation_target_language = hi
synth_language_code = hi-IN
synth_voice_name = hi-IN-MadhurNeural
synth_voice_gender = MALE

[LANGUAGE-3]
# Arabic
translation_target_language = ar
synth_language_code = ar-EG
synth_voice_name = ar-EG-ShakirNeural
synth_voice_gender = MALE

[LANGUAGE-4]
# Russian
translation_target_language = ru
synth_language_code = ru-RU
synth_voice_name = ru-RU-DmitryNeural
synth_voice_gender = MALE

[LANGUAGE-5]
# Portuguese
translation_target_language = pt
synth_language_code = pt-BR
synth_voice_name = pt-BR-FabioNeural
synth_voice_gender = MALE

[LANGUAGE-6]
# Italian
translation_target_language = it
synth_language_code = it-IT
synth_voice_name = it-IT-DiegoNeural
synth_voice_gender = MALE

[LANGUAGE-7]
# Indonesian
translation_target_language = id
synth_language_code = id-ID
synth_voice_name = id-ID-ArdiNeural
synth_voice_gender = MALE

[LANGUAGE-8]
# Japanese
translation_target_language = ja
synth_language_code = ja-JP
synth_voice_name = ja-JP-NaokiNeural
synth_voice_gender = MALE


[LANGUAGE-9]
# Korean
translation_target_language = ko
synth_language_code = ko-KR
synth_voice_name = ko-KR-BongJinNeural
synth_voice_gender = MALE

[LANGUAGE-10]
# German
translation_target_language = de
synth_language_code = de-DE
synth_voice_name = de-DE-KasperNeural
synth_voice_gender = MALE

[LANGUAGE-11]
# Chinese (Mandarin Simplified)
translation_target_language = zh
synth_language_code = zh-CN
synth_voice_name = zh-CN-YunyeNeural
synth_voice_gender = MALE

[LANGUAGE-12]
# Turkish
translation_target_language = tr
synth_language_code = tr-TR
synth_voice_name = tr-TR-AhmetNeural
synth_voice_gender = MALE

[LANGUAGE-13]
# TAMIL
translation_target_language = ta
synth_language_code = ta-IN
synth_voice_name = ta-IN-ValluvarNeural
synth_voice_gender = MALE

[LANGUAGE-14]
# FRENCE
translation_target_language = fr
synth_language_code = fr-FR
synth_voice_name = fr-FR-ClaudeNeural
synth_voice_gender = MALE

[LANGUAGE-15]
# URDU
translation_target_language = ur
synth_language_code = ur-PK
synth_voice_name = ur-PK-AsadNeural
synth_voice_gender = MALE

[LANGUAGE-16]
# DUTCH
translation_target_language = nl
synth_language_code = nl-NL
synth_voice_name = nl-NL-MaartenNeural
synth_voice_gender = MALE

[LANGUAGE-17]
# SWEDISH
translation_target_language = sv
synth_language_code = sv-SE
synth_voice_name = sv-SE-MattiasNeural
synth_voice_gender = MALE

[LANGUAGE-18]
# TELUGU
translation_target_language = te
synth_language_code = te-IN
synth_voice_name = te-IN-MohanNeural
synth_voice_gender = MALE

[LANGUAGE-19]
# THAI 
translation_target_language = th
synth_language_code = th-TH
synth_voice_name = th-TH-NiwatNeural
synth_voice_gender = MALE


[LANGUAGE-20]
# VIETNAMESE
translation_target_language = vi
synth_language_code = vi-VN
synth_voice_name = vi-VN-NamMinhNeural
synth_voice_gender = MALE


[LANGUAGE-21]
# BULGARIAN
translation_target_language = bg
synth_language_code = bg-BG
synth_voice_name = bg-BG-BorislavNeural
synth_voice_gender = MALE


[LANGUAGE-22]
# DANISH
translation_target_language = da
synth_language_code = da
synth_voice_name = da-DK-JeppeNeural
synth_voice_gender = MALE

[LANGUAGE-23]
# NORWEGIAN
translation_target_language = nb
synth_language_code = nb-NO
synth_voice_name = nb-NO-FinnNeural
synth_voice_gender = MALE

[LANGUAGE-24]
# CROATIAN
translation_target_language = hr
synth_language_code = hr-HR
synth_voice_name = hr-HR-SreckoNeural
synth_voice_gender = MALE

[LANGUAGE-25]
# GREEK
translation_target_language = el
synth_language_code = el-GR
synth_voice_name = el-GR-NestorasNeural
synth_voice_gender = MALE

[LANGUAGE-26]
# 
translation_target_language = en
synth_language_code = en-GB
synth_voice_name = en-GB-AlfieNeural
synth_voice_gender = MALE
`
And it generates the translated srt file and all the mp3 files of that translated srt file in the working folder, but any of them cant be played. It shows that**"an error occured during opeing the file"**. I think these mp3 files cannot be read by the program.It cannot be even read by my system mp3 player. and if there is some way that can you suggest for me to correct it, as it was all working fine but suddenly it stared throwing this error and I even redone the setup but it keeps throwing the same. Pls suggest me some ways regarding this error.

I even tried Spanish, which worked at first time, but now the separate audios from the working folder can't be opened/played for any language.

Thank You

**Comment by SweetSofiMC** [comment]
Hi! Are you using the setting `batch_tts_synthesize = False` and `tts_service = azure` under `cloud_service_settings.ini`?

If yes, are you using the most recent version of the software? There was a bug patch regarding these specific settings causing unplayable audio files, and it seems related to me, but could you please verify that?

**Comment by TharunDharmaraj** [comment]
Yeah, it said that batch synthesis is available only for Standard azure users. As I have a azure student plan, batch synthesis is set to false also I am using azure for text to speech.

**Comment by TharunDharmaraj** [comment]
Worked at the stable version 0.8.0
