### ISSUE TITLE
Having a large subtitles file causes a crash (chunk translation)

### ISSUE THREAD

**Issue by SweetSofiMC** [ThioJoe/Auto-Synced-Translated-Dubs#26]
The usage of batch translation causes the program to crash due to an list index out of range, as seen here:

```console
...
  File "Auto-Synced-Translated-Dubs\main.py", line 425, in translate_dictionary
    inputSubsDict[key]['translated_text'] = translatedTexts[i]
IndexError: list index out of range
```

This is due to the program iterating thru the chunks of translated text, and going to the range of the size of the whole list of texts to translate, causing it to crash if there are more than 100 texts in the srt file. 

The list will always have 100 chunks of text, but the `for` loop is going beyond that.

```python
main.py
                   Here's the problem
                           |
                           v
                   ------------------------
424| for i, key in enumerate(inputSubsDict):
425|                    inputSubsDict[key]['translated_text'] = translatedTexts[i]
426|                    # Print progress, ovwerwrite the same line
427|                    print(f' Translated: {key} of {len(inputSubsDict)}', end='\r')
```

**Comment by Alokkumar8** [comment]
its still causing crash. is this bug fixed. it crashed on this line in translate.py
` inputSubsDict[key]['translated_text'] = process_response_text(translatedTexts[i], targetLanguage)`
![image](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/assets/19433402/9d8c7250-f77e-406c-8b6a-8c8c32252a29)
