### ISSUE TITLE
KeyError: 'google_project_id'

### ISSUE THREAD

**Issue by oribeGames** [ThioJoe/Auto-Synced-Translated-Dubs#29]
![Captura de pantalla 2023-01-03 184347](https://user-images.githubusercontent.com/102562419/210464435-52567f12-ae65-4192-9944-b5df7dd8fada.jpg)

in "cloud service settings" change the values ​​of "google_project_id" and "your-project-name" to those of my account, I guess I did it right but I don't know why I don't get that

**Comment by SweetSofiMC** [comment]
You need to replace the value `your-project-name` with your project id and leave `google_project_id` unchanged since that's the reference for the configuration to work.

Here's an example of a working configuration in which the project name/id is `sweetsofimc-project`:
```ini
[CLOUD]
...
google_project_id = sweetsofimc-project
...
```
