### ISSUE TITLE
Google Colab Implement

### ISSUE THREAD

**Issue by elihat2022** [ThioJoe/Auto-Synced-Translated-Dubs#31]
I was trying to implement it in google colab, I don't know about programming, could someone continue to improve it?

https://colab.research.google.com/drive/1ox8rvSKtL1WBplJoeVET7Bv9eC6F-Plh?usp=sharing

**Comment by elihat2022** [comment]
<img width="975" alt="Captura de pantalla 2023-01-04 a la(s) 2 40 08 p m" src="https://user-images.githubusercontent.com/112003253/210636004-d930e136-da58-4df2-96bb-27386bc88ead.png">

**Comment by ThioJoe** [comment]
Considering that's literally the first line of code being read, it sounds like there are some major problems to be sorted out to get it to work in Colab, which I really don't see myself prioritizing, so just going to close this.
