### ISSUE TITLE
[Feature request] Add Lithuanian language

### ISSUE THREAD

**Issue by CattopyTheWeb** [ThioJoe/Auto-Synced-Translated-Dubs#34]
Add Lithuanian language for my fellow Lithuanian speakers, please.

**Comment by TharunDharmaraj** [comment]
`enabled_languages = 26

[LANGUAGE-26]
# LITHUANIAN
translation_target_language = lt
synth_language_code = lt-LT
synth_voice_name = lt-LT-LeonasNeural
synth_voice_gender = MALE

**Comment by MesVisiDraugai** [comment]
> `enabled_languages = 26
> 
> [LANGUAGE-26]
> 
> translation_target_language = lt synth_language_code = lt-LT synth_voice_name = lt-LT-LeonasNeural synth_voice_gender = MALE

nice, thanks

**Comment by MesVisiDraugai** [comment]
I'll make a pull request then

**Comment by MesVisiDraugai** [comment]
With your code if that's ok @TharunDharmaraj

**Comment by TharunDharmaraj** [comment]
Yeah, sure.
