### ISSUE TITLE
[Feature Suggestion/Bug Fix] Manual Review 

### ISSUE THREAD

**Issue by Sxigames** [ThioJoe/Auto-Synced-Translated-Dubs#35]
In some cases, auto-translation get message REALLY wrong, for example [RJ45 can get translated as Rio de Janeiro 45](https://youtu.be/ZCbg52OUlyk?t=17), so a manual review option would be great!

**Comment by ThioJoe** [comment]
The translation was actually correct, but the voice spoke it wrong. Plus it can be manually reviewed by looking at the subtitle files.
