### ISSUE TITLE
HTTPError during runninf main.py

### ISSUE THREAD

**Issue by a-russkikh** [ThioJoe/Auto-Synced-Translated-Dubs#42]
Hi!
Could someone help me with this error please?

----- Beginning Processing of Languages -----
----- Beginning Processing of Language: es-MX -----
Translating text using Google...

    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://translation.googleapis.com/v3beta1/projects/sasa:translateText?alt=json returned "Empty request.". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'contents', 'description': '**_****No text contents provided.'}]}]">**_****

![image](https://user-images.githubusercontent.com/69730626/211930324-e55b4092-1213-4e62-8fd8-776836237ae6.png)

**Comment by ThioJoe** [comment]
Can you provide your original srt file?

**Comment by a-russkikh** [comment]
PFA, I made it manually by the way. But I used a template from another srt file.

[subtitles.zip](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/files/10402260/subtitles.zip)


> Can you provide your original srt file?

**Comment by ThioJoe** [comment]
Ah, those subtitles don't appear to have the correct format for the timestamps. 

See [this article](https://en.wikipedia.org/wiki/SubRip#SubRip_file_format)

> The [timecode](https://en.wikipedia.org/wiki/Timecode) format used is hours:minutes:seconds,milliseconds with time units fixed to two zero-padded digits and fractions fixed to three zero-padded digits (00:00:00,000). The [fractional separator](https://en.wikipedia.org/wiki/Decimal_separator#History) used is the [comma](https://en.wikipedia.org/wiki/Comma), since the program was written in France.
