### ISSUE TITLE
Problem with synchronization 

### ISSUE THREAD

**Issue by Rovi23** [ThioJoe/Auto-Synced-Translated-Dubs#45]
Hello!

I present a problem with the synchronization of the original audio and the translated audio.

Some languages are much more concise than others. For example, English vs Spanish. Normally more words are needed to express something in Spanish than it takes to say the same thing in English.

I give a concrete example:

`1`
`00:00:00,100 --> 00:00:06,195`
`¿Qué creéis que ocurriría si mezclamos los personajes de Poppy Playtime con los personajes de Rainbow Friends?`

As you can see, this phrase needs 6 seconds to be spoken. However, the translation would be this:

`1`
`00:00:00,100 --> 00:00:06,195`
`What do you think would happen if we mix Poppy Playtime with the Rainbow Friends characters?`

And the resulting unsynced audio takes 4 seconds:

[1.mp3.zip](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/files/10417205/1.mp3.zip)

When synchronizing the English audio it is forced to 6 seconds which produces a very unsatisfactory result (very slow).

[1.mp3.zip](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/files/10417214/1.mp3.zip)

Would there be a way to tell the program that, in the case of such a difference between the times of the languages, apply a maximum of X seconds between the original and the translation? For example max_diff = 1000ms. In this way the audio in English would last 6 seconds instead of 7 and it would not be so weird.

This is especially useful in videos where there is no camera and synchronization is not strictly necessary (if there are empty gaps without audio, the video could be clipped).

Best!

**Comment by ThioJoe** [comment]
Ok, I realized the function that was combining the subtitles was totally messed up. It _should_ be fixed with the latest version, 0.9.1
