### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by TiltedChris** [ThioJoe/Auto-Synced-Translated-Dubs#46]
I got following problem:

googleapiclient.errors.HttpError: <HttpError 403 when requesting https://translation.googleapis.com/v3beta1/projects/third-framing-374214:translateText?alt=json returned "Cloud Translation API has not been used in project 234603848874 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/translate.googleapis.com/overview?project=234603848874 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console API activation', 'url': 'https://console.developers.google.com/apis/api/translate.googleapis.com/overview?project=234603848874'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'SERVICE_DISABLED', 'domain': 'googleapis.com', 'metadata': {'service': 'translate.googleapis.com', 'consumer': 'projects/234603848874'}}]">

**Comment by ThioJoe** [comment]
What happens when you follow the link and try to enable it like it says?

**Comment by TiltedChris** [comment]
Do I need the cloud text-to-speech api because it gives my a price list but as far as I remember you said in your video this is for custom voices

**Comment by ThioJoe** [comment]
I guess right now you still need to enable the API even if you are just using Azure, because the program is written to assume you have it enabled.
