### ISSUE TITLE
Add parallel to trimm audio

### ISSUE THREAD

**Issue by SlimRG** [ThioJoe/Auto-Synced-Translated-Dubs#53]
One of the slowest moments
You shouldn't use only one cpu's core

**Comment by SlimRG** [comment]
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/39348033/218337114-902363ad-fcf7-4f59-97b4-3d6024f4d524.png">

**Comment by ThioJoe** [comment]
True, but it is something I'd have to learn to do. I am not familiar with multi-core or multi-processor programming

**Comment by ThioJoe** [comment]
I tested implementing parallel processing with both multithreading and multiprocessing. It worked, but it was actually slower than doing it sequentially. Python sucks at doing parallel processing. It might be possible, but I'm not going to spend any more time on it.
