### ISSUE TITLE
skip translation and do synthesizing only still impossible

### ISSUE THREAD

**Issue by benshgit** [ThioJoe/Auto-Synced-Translated-Dubs#57]
I set skip_translation=true, I want it to synthesize with Azure, and run the main.py, then it gives the following message:
------- 'Auto Synced Translated Dubs' script by ThioJoe - Release version 0.13.0 -------

         ----- [!] Error: client_secrets.json file not found -----
 ----- Did you create a Google Cloud Platform Project to access the API? -----

Press Enter to Exit...

**Comment by ThioJoe** [comment]
Ok try the new 0.13.1 release, that should fix it
