### ISSUE TITLE
Can we simplfy the install instructions on the front page?

### ISSUE THREAD

**Issue by KNection** [ThioJoe/Auto-Synced-Translated-Dubs#75]
On the external requirements:
"You'll need the binaries for a program called 'rubberband' ( http://breakfastquay.com/rubberband/ ).  Doesn't need to be installed, just put both exe's and the dll file in the same directory as the scripts.

I need more context than what is given.  First there are no exe's or dll file in the download provided here and I don't know what scripts are being implied to put with them if I'm over looking them.

![image](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/assets/130387631/fdbcc8c4-6022-47f7-8551-1d7450eb4137)

**Comment by Alokkumar8** [comment]
I have same issue

**Comment by DablewCodes** [comment]
The instructions are correct, You need to go to https://breakfastquay.com/rubberband/, download the 'Rubber Band Library v3.3.0 command-line utility' for Windows, extract the two .exe and one .dll file, and place them inside the project folder.

**Comment by ThioJoe** [comment]
I've updated the readme section to be more specific on which files are needed and how to download them.
