### ISSUE TITLE
ElevenLabs Error 400

### ISSUE THREAD

**Issue by RafaelGodoyEbert** [ThioJoe/Auto-Synced-Translated-Dubs#84]
![image](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/assets/78083427/ade5e9cd-bcb7-4588-a450-7758b12373c6)
When I use ElevenLabs together with the API, I get this error.

**Comment by ThioJoe** [comment]
Hm I’ll have to investigate. But I think it might be because elevenlabs returned an error. Notice how up higher it says “Error 400”. So it didnt return a file which would explain why the script couldn’t find one. I’ll have to add more detailed error handling so it’s more obvious what the problem is exactly.

**Comment by ThioJoe** [comment]
With the latest release it should provide a proper error message to explain what went wrong.

**Comment by RafaelGodoyEbert** [comment]
Yes, I placed the API in the correct location. 

Below the error appeared

![image](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/assets/78083427/9d81ae0a-f0c1-425d-9119-229cde5c4d13)

But in the end I created my own code to work with my API

So for me it's ok, I'm already using elevenlabs with my additional code, I just changed some things to recognize it.

I'm just contacting you to alert you to the error.

If you correct or find the solution or error I'm making, I'll use your code again.


```
import asyncio
from elevenlabs import generate, set_api_key
import os
import sys

async def generate_tts(text, output_file, voice):
    audio_data = generate(
        text=text,
        voice=voice,
        model='eleven_multilingual_v2'
    )
    with open(output_file, "wb") as audio_file:
        audio_file.write(audio_data)

async def amain(text, languageCode, output_folder, subtitle_num) -> None:
    try:
        set_api_key("API_KEY")
        # O código relacionado ao mapeamento de voz não é necessário com a API Eleven Labs,
        # pois a API já lida com a seleção de voz.
        voice = "Charlie"  # Substitua pela voz desejada
    except Exception as e:
        print(f"Exceção: {e}")

    if voice:
        if not os.path.exists(output_folder):
            os.makedirs(output_folder)

        tts_output_file = os.path.join(output_folder, f"{subtitle_num}.mp3")

        await generate_tts(text, tts_output_file, voice)

    else:
        print(f"Idioma {languageCode} não suportado.")
        print(f"Lang Code: '{languageCode}'")
        print(f"Voice: {voice}")

def main():
    if len(sys.argv) != 5:
        print("Uso: python srt2edge-tts.py <texto> <lang_code> <output_folder> <subtitle_num>")
        sys.exit(1)

    text = sys.argv[1]
    lang_code = sys.argv[2]
    output_folder = sys.argv[3]
    subtitle_num = sys.argv[4]

    # Define output_folder para a pasta "workingFolder" um nível acima do diretório atual
    output_folder = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'workingFolder'))

    asyncio.run(amain(text, lang_code, output_folder, subtitle_num))

if __name__ == "__main__":
    main()
```

**Comment by ThioJoe** [comment]
Did you read the error message? It mentions en-US-JasonNeural, which would be the default voice currently selected in the batch.ini file, which is an Azure voice. You have to set an ElevenLabs voice. You can find the IDs for voices like this: https://help.elevenlabs.io/hc/en-us/articles/14599760033937-How-do-I-find-my-voices-ID-of-my-voices-via-the-website-and-through-the-API-

**Comment by RafaelGodoyEbert** [comment]
Yes, I read until the end and saw that it was en-US-JasonNeural. At first, when you posted 17.0 I just tried to change it to some name that is there, like 'Adam'.

Now it's clear that it has to be the ID codes, which I can find more specifically at this link https://api.elevenlabs.io/v1/voices

Thanks for the feedback.

![image](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/assets/78083427/65fe1af3-0f7c-4f84-8033-8dbea177739b)

**Comment by ThioJoe** [comment]
Yea I've just added a new release that should provide more details about at least two invalid voice errors
